### PR TITLE
Added all the scss files as main in bower.json

### PR DESCRIPTION
**Pull request by hass-isnull**
Given that scss uses @imports to include other scss file, I've added the list of scss files in the main file section to the bower.json. This is to help tools like grunt and gulp to fetch/minify (or whatever they want to use) to collect all the files.

### CODE REVIEW

**Comment by cvrebert** [comment]
@hass-isnull Do you have an example of a Bower-consuming tool that requires this? Bower doesn't currently define the semantics of `main` with regard to Sass and Less.

**Comment by hass-isnull** [comment]
you can use gulp combined with the module main-bower-files to consume the main files defined in bower.json.
glup - https://www.npmjs.com/package/gulp
maib-bower-files - https://www.npmjs.com/package/main-bower-files

**Comment by cvrebert** [comment]
:-1: This makes the notion of `main` meaningless.

**Comment by hass-isnull** [comment]
Maybe you can advise how `main` should be used? or even link something which does?
Thanks!

**Comment by cvrebert** [comment]
Bower is currently vague on `main`'s definition, and they have shown no signs of resolving the issue any time soon :angry:. *De facto* usage in the wild for CSS preprocessor code seems to be "include only the single 'main' Less/Sass/Stylus/whatever file that imports all the other style files".

* https://github.com/bower/bower.json-spec#main
* https://github.com/bower/bower.json-spec/issues/36#issuecomment-54575889
* https://github.com/twbs/bootstrap-sass/pull/586#issuecomment-40976663
* https://github.com/bower/bower/issues/935
* https://github.com/bower/bower.json-spec/pull/6#issuecomment-57558834

Speaking personally, my advice is not to use Bower.
Closing as an approximate duplicate of #586 now that I've rediscovered that past PR.

**Pull request closed without merging**
