### PR TITLE
Fix nested division

### PR DESCRIPTION
**Pull request by AprilArcus**
Fixes less -> sass conversion bug impacting nested parentheses

see https://github.com/twbs/bootstrap-sass/pull/1221#discussion_r815313181

### CODE REVIEW

**Comment by AprilArcus** [comment]
@glebm did you intend to merge this into `master` and not `sass-modules` or `twbs:sass-modules`, as you did with https://github.com/twbs/bootstrap-sass/pull/1221?

**Comment by glebm** [comment]
I've merged straight to master, figured the complication with multiple branches is not worth it

**Comment by glebm** [comment]
Pushed 3.4.3

**Comment by glebm** [comment]
Thanks for the quick fix!

**Comment by AprilArcus** [comment]
it's a pleasure working with you

**Pull request merged**
