### PR TITLE
Bootstrap 4 alpha support

### PR DESCRIPTION
**Pull request by JanStevens**
Hello,

This little MR adds support for Bootstrap 4 and destructively ends support for Bootstrap 3. I've removed any less conversion and now pull the scss files directly from the 4-dev branch.

Feel free to take a look and work with the latest bootstrap 4 alpha code in your Rails application. I suggest this gets released as version 4 and then follow bootstrap versioning (since this gem only pulls data and package it and does not do any fancy stuff anymore with converting less to scss)

## Still to do

- [x] Removed unused test
- [ ] Updated Readme to reflect the new bootstrap 4 changes
- [x] Wait for upstream fix of bootstrap flex compilation (https://github.com/twbs/bootstrap/issues/17046)

### CODE REVIEW

**Comment by thomas-mcdonald** [comment]
Thanks for this! We haven't yet had much of an internal discussion about what the plans for this project are when v4 goes live.

**Comment by JanStevens** [comment]
Maintaining it will be a piece of cake since it only repacks the scss and js files so not many issues will pop up.

Only concern is the ever changing pace of Rails/Sprockets ofcourse :)

The real beauty is that this gem ONLY includes Bootstrap and does not import any "helpers".

Hope we keep the official gem alive!

Regards

**Comment by glebm** [comment]
Hi @JanStevens, thanks a lot for this work! I have started a different repo for the v4 rubygem from this branch as per the discussion in https://github.com/twbs/bootstrap/issues/17291. The new repo will be published soon. Cheers, Gleb

**Comment by JanStevens** [comment]
@glebm Can I keep pushing to this branch or wait for the new repo? Was planning on adding generators for rails so people can easily install bootstrap (or one of its variants)

Cheers!

**Comment by glebm** [comment]
@JanStevens Please wait for the new repo as I've made some commits as well, shouldn't be long!

**Comment by glebm** [comment]
Published in https://github.com/twbs/bootstrap-rubygem

**Comment by glebm** [comment]
Since the scope of the project has been reduced to just the rubygem, the docs will need rewriting. For now I've put a stub README.md to indicate that the repo is a work in progress.

**Pull request closed without merging**
